config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'events/index', to: 'events#index', as: 'events'

  get 'events/new', to: 'events#new', as: 'new_event'

  post 'events/index', to: 'events#create'

  get 'events/:id', to: 'events#show'

  get 'tickets/mytickets/:id', to: 'tickets#show_user_tickets', as: 'my_tickets'

  get 'money/index', to: 'money#index', as: 'show_me_my_money'

  post 'money/create', to: 'money#create', as: 'give_me_my_money'

  get 'tickets/arena/:id', to: 'tickets#show_arena', as: 'show_arena'

  root :to => 'events#index'

  resources :tickets
  resources :events, :only => [:index, :new, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :artist, :presence => true
  validates :price, :presence => true, numericality: true
  validates :event_date, :presence => true
  validate :valid_date?
  validates :seat_count, :presence => true, numericality: true
  validates :rows, :presence => true, numericality: true
  validate :seat_row?
  validate :rows_dividable?

  validates :image, attachment_presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :tickets

  def seat_row?
    if seat_count/rows > 25
      errors.add('Seat count','maximum of 25 seats in a row')
    end
  end

  def rows_dividable?
    if seat_count % rows != 0
      errors.add('Seat count', 'needs to dividable by rows')
    end
  end

  def valid_date?
    if event_date.past?
      errors.add('Event date','cannot be from the past')
    end
  end

  def seats_left
    seat_count - tickets.flat_map{|t| [t.seat1,t.seat2,t.seat3,t.seat4,t.seat5]}.select{|seat| !seat.blank?}.length
  end

  def is_today
    if event_date == Date.today
      return true
    end
    false
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :admin_user, only: [:new, :create, :destroy]

  def index
    @events = Event.where('event_date >= ?', Date.today ).order(event_date: :asc)
    @archive_events = Event.where('event_date < ?', Date.today )
  end

  def show
    @event = Event.find(params[:id])
    @tickets = Ticket.where(:event_id => @event.id)
    @ticket = Ticket.new(:event_id => @event.id, :price => 0.0)
      if current_user
        @ticket.user_id = current_user.id
        @ticket.email_address = current_user.email
      end
  end

  def new
    @event = Event.new
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:komunikat] = 'Event was successfully created.'
      redirect_to "/events/#{@event.id}"
    else
      render 'new'
    end

  end

  def destroy
    if !current_user.is_admin
      redirect_to events_path, alert: "Only admistrator can remove events!"
      return
    end

    @event = Event.find(params[:id])
    @event.ticket.each{|t| t.destroy}
    @event.destroy

    redirect_to events_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def admin_user
    if !current_user.is_admin
      redirect_to events_path, alert: "Only administrator can perform this action!"
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:artist, :description, :price, :event_date, :image, :adults_only, :seat_count, :rows)
  end



end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
            <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group required">
      <%= form.label :artist %>
      <%= form.text_field :artist, id: :event_artist , class: "form-control"%>
    </div>

    <div class="form-group required">
      <%= form.label :description %>
      <%= form.text_area :description, id: :event_description, class: "form-control" %>
    </div>

    <div class="form-group required">
      <%= form.label :price %>
      <%= form.text_field :price, id: :event_price, class: "form-control" %>
    </div>

    <div class="form-group required">
      <%= form.label :adults_only %>
      <%= form.check_box :adults_only, id: :event_adults_only %>
    </div>

    <div class="form-group required">
      <%= form.label :event_date %>
      <%= form.date_select :event_date, class: "form-control"%>
    </div>

    <div class="form-group required">
      <%= form.label :seat_count %>
      <%= form.text_field :seat_count, id: :event_seat_count, class: "form-control" %>
    </div>

    <div class="form-group required">
      <%= form.label :rows %>
      <%= form.text_field :rows, id: :event_rows, class: "form-control" %>
    </div>

    <div class="form-group required">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>


    <div class="actions">
      <%= form.submit "Create event", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/events/_new_ticket.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
    <% if ticket.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

          <ul>
            <% ticket.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group required">
      <%= form.label :name %>
      <%= form.text_field :name, id: :ticket_name , class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_area :address, id: :ticket_address , class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.label :email_address %>
      <%= form.text_field :email_address, id: :ticket_email_address, :readonly => true, class: "form-control" %>
    </div>

    <div class="form-group required">
      <%= form.label :phone %>
      <%= form.text_field :phone, id: :ticket_phone , class: "form-control"%>
    </div>

    <div class="form-group">
      <%= form.label :price %>
      <% if @event.is_today %>
          <p style="color: red">
          20% extra for same day delivery
          </p>
      <% end %>
      <%= form.text_field :price, id: :ticket_price, :readonly => true, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label "Seats" %>
      <%= form.text_field :seat1, id: :ticket_seat1 ,:readonly => true%>
      <%= form.text_field :seat2, id: :ticket_seat2 ,:readonly => true%>
      <%= form.text_field :seat3, id: :ticket_seat3 ,:readonly => true%>
      <%= form.text_field :seat4, id: :ticket_seat4 ,:readonly => true%>
      <%= form.text_field :seat5, id: :ticket_seat5 ,:readonly => true%>
    </div>

    <div class="field">
      <%= form.hidden_field :user_id, id: :ticket_user_id %>
    </div>

    <div class="field">
      <%= form.hidden_field :event_id, id: :ticket_event_id %>
    </div>

    <div class="actions">
      <%= form.submit "Buy ticket", class: "btn btn-primary" %>
    </div>

<% end %>

app/views/events/_tickets_list.html.erb
<div class="row">
  <div class="col text-center">
    <h1>Tickets</h1>
  </div>
</div>
<div class="row">
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
      <tr>
        <th>Name</th>
        <th>Seats</th>
        <th>Address</th>
        <th>Price</th>
        <th>Email address</th>
        <th>Phone</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @tickets.each do |ticket| %>
          <tr>
            <td><%= ticket.name %></td>
            <td><%= ticket.seat1.to_s  %>
            <%= "," + ticket.seat2.to_s  %>
            <%= ',' + ticket.seat3.to_s  %>
            <%= "," + ticket.seat4.to_s  %>
            <%= "," + ticket.seat5.to_s  %>
            </td>
            <td><%= ticket.address %></td>
            <td><%= ticket.event.price %></td>
            <td><%= ticket.email_address %></td>
            <td><%= ticket.phone %></td>
            <td><%= link_to 'Show', ticket %></td>
            <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
            <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>

          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/events/index.html.erb
<div class="row">
  <div class="col text-center">
    <h1>Events</h1>
  </div>

</div>

<div class="row">
  <% for event in @events %>
      <div class="col-md-4">
        <%= link_to event do %>
            <div class="square" style="background-image: url(<%= event.image.url(:medium) %>)">
              <div class="squareTest">
                <%= event.artist %>
              </div>
            </div>
        <% end %>
      </div>
  <% end %>
</div>

<% if current_user && current_user.is_admin %>
<div class="row">
  <div class="col text-center">
    <h1>Archived events</h1>
  </div>
</div>

<div class="row">
  <% for event in @archive_events %>
      <div class="col-md-4">
        <%= link_to event do %>
            <div class="square" style="background-image: url(<%= event.image.url(:medium) %>)">
              <%= event.artist %>
            </div>
        <% end %>
      </div>
  <% end %>
</div>
<% end %>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-8" style="margin: 0 auto;">
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col text-center">
            <h1>Event new</h1>
          </div>
        </div>
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <div class="table-responsive">
          <table class="table table-bordered">
            <tr>
              <th>Artist</th>
              <td><%= @event.artist %></td>
            </tr>
            <tr>
              <th>Description</th>
              <td><%= @event.description %></td>
            </tr>
            <tr>
              <th>Base price</th>
              <td><%= @event.price %></td>
            </tr>
            <tr>
              <th>Date</th>
              <td><%= @event.event_date %></td>
            </tr>
            <tr>
              <th>Adults only</th>
              <td><% if @event.adults_only %>Yes<% else %>No<% end %></td>
            </tr>
            <tr>
              <th>Total seats</th>
              <td><%= @event.seat_count %></td>
            </tr>
            <tr>
              <th>Available seats</th>
              <td><%= @event.seats_left %></td>
            </tr>
          </table>
        </div>
      </div>
      <div class="col-md-8 .img-responsive" style="margin: auto;">
        <%= image_tag @event.image.url(:medium) %>
      </div>
    </div>

  </div>
</div>

<div class="card">
  <div class="card-body">
    <% if current_user %>
      <% if current_user.is_admin %>
          <%= render "tickets_list", tickets: Ticket.all %>
      <% else %>
        <div class="row">
          <div class="col-md-4">
            <%= render "new_ticket", ticket: @ticket %>
          </div>
          <div class="col-md-8">
            <%= render partial: 'arena/arena_view', locals: { event: @event, tickets: @tickets} %>
          </div>
        </div>
      <% end %>
    <% else %>
      <%= link_to 'Buy ticket', new_ticket_path,class: "btn btn-success" %>
    <% end %>
  </div>
</div>