config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'events/index', to: 'events#index', as: 'events'

  get 'events/new', to: 'events#new', as: 'new_event'

  post 'events/index', to: 'events#create'

  get 'events/:id', to: 'events#show'

  get 'tickets/mytickets/:id', to: 'tickets#show_user_tickets', as: 'my_tickets'

  get 'money/index', to: 'money#index', as: 'show_me_my_money'

  post 'money/create', to: 'money#create', as: 'give_me_my_money'

  get 'tickets/arena/:id', to: 'tickets#show_arena', as: 'show_arena'

  root :to => 'events#index'

  resources :tickets
  resources :events, :only => [:index, :new, :create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= link_to 'Events list', events_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
          <% if current_user.is_admin %>
              <li>
                <%= link_to 'Add new event', new_event_path, class: "nav-link" %>
              </li>
          <% end %>
      <% end %>
      <% if user_signed_in? %>
          <li>
            <%= link_to 'Tickets list', my_tickets_path(current_user.id), class: "nav-link" %>
          </li>
      <% end %>
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Buy ticket', new_ticket_path, class: "nav-link" %>
        </li>
      <% end %>
      <% if user_signed_in? %>
          <li>
            <%= link_to 'Money', show_me_my_money_path, class: "nav-link" %>
          </li>
      <% end %>
    </ul>
    <span class="navbar-text navbar-right">
      <% if user_signed_in? %>
        <% if current_user.is_admin %>
          Logged in as <strong>Administrator</strong>.
        <% else %>
          Logged in as <strong><%= current_user.email %></strong>.
        <% end %>

          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'%>
      <% end %>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketSlave</title>
    <%= csrf_meta_tags %>

    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
          integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
  </head>

  <body>

  <%= render 'layouts/navigation' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container" style=" margin-bottom: 10px">
  <%= yield %>
  </div>

  </body>
</html>